### ISSUE TITLE
Build the Tier 3 signed release path and the four hostile images

### ISSUE THREAD

**Issue by tkEmLogic** [tkEmLogic/learning-cyber-security#56]
## Question

Build it.

- The key-generation command, the file layout under `.course-secrets/`, and the guard that refuses to replace an existing key silently.
- The signing step and the publishing path, in the shape [Decide what the Learner authors in Tier 3] settled.
- The build-time generation of the four hostile images from the Learner's own good image, and the attacker key that the same command makes.
- The fixtures, in the shape [Decide the Tier 3 fixture set and what a refusal must show] settled, obeying `docs/fixture-safety-contract.md` as extended.
- The proof that the OTA service container cannot read `.course-secrets/`.
- `scripts/check-secrets.sh` and `.gitignore` updated so a private key cannot reach Git.

Every command narrates. A command that performs an attack silently and prints `Result: it worked` teaches nothing.

Host validation may prove that a fixture offers the right bytes and that the guardrails hold. It may not claim the device refused anything. That is the next ticket's job.

Run `scripts/verify-tier-00.sh` before committing. Commit to `main` and push.

**Comment by tkEmLogic** [comment]
## Resolution

Built, on `main`, in four commits. Everything below was run rather than assumed.

### The build never names the Release signing key, and that cost a redesign

`SB_CONFIG_BOOT_SIGNATURE_KEY_FILE` is one value feeding two jobs: `imgtool getpub` for the bootloader, which needs only the public half, and `imgtool sign` for the application, which needs the private half. One value cannot be both. Four ways to reconcile that inside sysbuild were tried and each fails:

- An application level `sysbuild.cmake` is included **before** the image defaults, so its overrides are discarded.
- An app scoped `EXTRA_CONF_FILE` loses to the image CONFIG property, which sysbuild applies last.
- `SB_CONFIG_BOOT_SIGNATURE_TYPE_NONE` turns verification off in the bootloader too, not just signing in the application.
- Pointing the one value at the public key fails the application build with `'ECDSA256P1Public' object has no attribute 'sign_digest'`.

So the two images are built separately. `./course build firmware --tier 03` runs sysbuild to get the application **unsigned** and throws away the bootloader it produces, then builds the bootloader that ships from `firmware/tier-03-signed-images/bootloader/mcuboot.conf` against the public half alone.

That split is verified rather than trusted. The separately built bootloader resolves to a Kconfig identical to sysbuild's except for the key file path, and to the same binary size. Building outside sysbuild means restating what sysbuild injects, so the bootloader config sets the upgrade mode explicitly with every other mode off, exactly as `BOOTLOADER_image_default.cmake` does.

### Signing is the Learner's step

The build publishes nothing. An unsigned image is not a release, because the device refuses it, and saying so is more useful than quietly producing one.

`./course release sign` is the only place the private key is named. It prints the fingerprint of the key it used and the digest of what it published.

### The four hostile images are made, not shipped

`./course release hostile` derives them from the good image the Learner just signed. Nothing hostile is committed, so a fork of this repository never carries a ready made attack payload.

The attacker key comes from the same command as the Release signing key, and `./course keys list` prints both fingerprints side by side under a line saying both are equally valid and only the fingerprint compiled into the bootloader decides. That is `CTL-06` in a command rather than a paragraph.

### The fixture refuses nothing, and says so

`tier-03/hostile-image` publishes one image through the genuine service over the connection the device verifies. The image is chosen by `--image` against an allowlist in `course.yml`, never as a path, so the fixture cannot be talked into serving arbitrary bytes to a board. A missing or unknown selector is refused before anything happens.

Its last step is `Stop. Nothing here can refuse this image.` The evidence record says the device outcome is not known to the fixture, because it is not. This is [Decide the Tier 3 fixture set and what a refusal must show](https://github.com/tkEmLogic/learning-cyber-security/issues/55) implemented literally.

Real output from step 2, which is the sentence the whole tier turns on:

```text
     The record even says "signed": true. Nothing checks that, and nothing ever has.
```

### Four smaller things

`./course keys create` refuses to replace an existing key, prints its fingerprint, and makes the Learner type the `rm`. There is no `--replace` flag.

The reported fingerprint is the SHA-256 of the DER public key, checked against a real signed image's `KEYHASH` TLV rather than assumed, because the Tier 3 boot line will report this number.

`scripts/check-secrets.sh` had a filename pattern reading `.*\\.key`, where the doubled backslash demanded a literal backslash in the name. `release.key` and `release.pem` both walked past it and only `id_rsa` and `id_ed25519` were ever caught. It now also refuses anything staged under `.course-secrets/`, because `.gitignore` is advice and `git add -f` ignores it.

`course.yml` gains the `tier-03-baseline` variant with `image_mode: signed_ecdsa_p256`, the fixture with its image allowlist, and `mentor_review: required`. The Release signing key is deliberately **absent** from the manifest: it is named by `./course release sign` and nowhere else.

### Tests

Five, each guarding something that would fail quietly. A modified image identical to the good one, a truncation of zero bytes, an evidence record missing its selector, a later tier dropping back to plain HTTP for release data, and a third key role arriving without a decision about whether a build may read it.

### What this ticket did not do

The application sources are still Tier 2's, so the board still prints a Tier 2 banner. The boot line reporting which key the device trusts, and the board proof of all five outcomes, belong to [Make the Reference product refuse hostile firmware, and prove it on the board](https://github.com/tkEmLogic/learning-cyber-security/issues/57).
